# примеры API-запросов

@baseUrl = http://localhost:8000/api/v1

# создание продукта
POST {{baseUrl}}/products/
Content-Type: application/json

{
  "title": "Повидло",
  "description": "Из Польши"
}

###

# получение продуктов
GET {{baseUrl}}/products/
Content-Type: application/json

###

# обновление продукта
PATCH {{baseUrl}}/products/1/
Content-Type: application/json

{
  "description": "Самые сочные и ароматные помидорки"
}

###

# удаление продукта
DELETE {{baseUrl}}/products/1/
Content-Type: application/json

###

# поиск продуктов по названию и описанию
GET {{baseUrl}}/products/?search=помидор
Content-Type: application/json

###

# создание склада
POST {{baseUrl}}/stocks/
Content-Type: application/json

{
  "address": "Заречная 5",
  "positions": [
    {
      "product": 8,
      "quantity": 150,
      "price": 36
    },
    {
      "product": 10,
      "quantity": 1000,
      "price": 900
    }
  ]
}

###
GET {{baseUrl}}/stocks/
Content-Type: application/json

###
# обновляем записи на складе
PATCH {{baseUrl}}/stocks/10/
Content-Type: application/json

{
  "positions": [
    {
      "product": 1,
      "quantity": 10030,
      "price": 130.80
    },
    {
      "product": 6,
      "quantity": 1000000,
      "price": 145
    }
  ]
}

###

# поиск складов, где есть определенный продукт
GET {{baseUrl}}/stocks/?products=2
Content-Type: application/json
